#visualization using r
library(RColorBrewer)
data("VADeaths")
par(mfrow=c(1,1))
hist(VADeaths,breaks=10,col=brewer.pal(3,"Set1"),main="set 3,3 colors")
hist(VADeaths,breaks=2,col=brewer.pal(2,"Set2"),main="set 3,3 colors")
hist(VADeaths,breaks=3,col=brewer.pal(1,"Set3"),main="set 3,3 colors")
hist(VADeaths,breaks=4,col=brewer.pal(3,"Set3"),main="set 3,3 colors")
hist(VADeaths,breaks=5,col=brewer.pal(8,"Set3"),main="set 3,3 colors")
plot(AirPassengers,type="l")
barplot(iris$Sepal.Length)
barplot(iris$Sepal.Length,col=iris$Species,col=brewer.pal(3,"Set1")
barplot(iris$Sepal.Length,col=brewer.pal(3,"Set1"))
barplot(table(iris$Species,iris$Sepal.Length),col=brewer.pal(3,"Set1"))
plot(x=iris$Sepal.Length)
plot(x=iris$Sepal.Length,y=iris$Species.Width,col=iris$Species)
plot(iris,col=brewer.pal(3,"Set1"))
pie(table(iris$Species))
table(iris$Species)
#advanced visualisations
install.packages("hexbin")
library(hexbin)
a=hexbin(iris$Sepal.Length,iris$Species)
plot(a)
rf <- colorRampPalette(rev(brewer.pal(3,'Set3')))
hexbinplot(diamonds$price~diamonds$carat,data=diamonds,colramp=rf)
#heatmaps-can only use heat maps for matrices
heatmap(as.matrix(mtcars))
image(as.matrix(mtcars[2:7]))
install.packages("devtools")
install.packages("curl")
library(devtools)
devtools::install_github("rstudio/leaflet")
#3d maps with r
install.packages("Rcmdr")
library(Rcmdr)
data(iris,package = "datasets")
scatter3d(Petal.Width~Petal.Length+Sepal.Length|Species, data=iris, fit="linear"
residuals=TRUE, parallel=FALSE, bg="black", axis.scales=TRUE, grid=TRUE, ellipsoid=FALSE)
attach(iris)
cloud(Sepal.Length~Sepal.Width*Petal.Length|Species,main="3d")
xyplot(Sepal.Width ~ Sepal.Length,iris,groups=iris$Species,pch=20)
